### ISSUE TITLE
[Fixed] Module blocking app Face Recognition

### ISSUE THREAD

**Issue by Stillhard** [canyie/Riru-IsolatedMagiskHider#3]
App using that feature is blocked, and [MagiskDetector](https://github.com/vvb2060/MagiskDetector) is not running properly (some lines not shows) but still detecting some of Magisk thing.

**Comment by canyie** [comment]
> MagiskDetector is not running properly (some lines not shows)

Because of MagiskDetector can't detect su file, so it hides some rows. See https://github.com/vvb2060/MagiskDetector/blob/master/app/src/main/java/io/github/vvb2060/magiskdetector/MainActivity.java#L181

> but still detecting some of Magisk thing

Do you mean "init.rc has been modified", "SELinux policy has been modified" or "found running su processes"? Currently I have no way to hide them.

**Comment by Stillhard** [comment]
> "init.rc has been modified"

Yes, this one

> Currently I have no way to hide them.

It's alright then

**Comment by canyie** [comment]
> > "init.rc has been modified"
> 
> Yes, this one
> 
Published a way to hide this, you can enable it by create the file /data/misc/isolatedmagiskhider/initrc
Note: MagickDetector saves the previous properties, you need to clear its data to make it read again.

**Comment by Stillhard** [comment]
> > > "init.rc has been modified"
> > 
> > 
> > Yes, this one
> 
> Published a way to hide this, you can enable it by create the file /data/misc/isolatedmagiskhider/initrc
> Note: MagickDetector saves the previous properties, you need to clear its data to make it read again.

tried with initrc and init.rc (one is not enough to be sure lol)
Test results: Need to restart to complete detection

```
2021-03-13 16:51:03.194 1428-1953/? D/AMS: isProcStartable in LRU io.github.vvb2060.magiskdetector return true
2021-03-13 16:51:03.202 306-306/? I/IsolatedMagiskHider: Changed mount mode from MOUNT_EXTERNAL_NONE to MOUNT_EXTERNAL_DEFAULT
2021-03-13 16:51:03.216 1428-1953/? I/ActivityManager: AMS: *** Start proc 4825:io.github.vvb2060.magiskdetector/u0i3 for service io.github.vvb2060.magiskdetector/.RemoteService
2021-03-13 16:51:03.233 4825-4825/? I/IsolatedMagiskHider: Created isolated process or app zygote 4825, starting magisk hide...
2021-03-13 16:51:03.301 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/xbin)
2021-03-13 16:51:03.361 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/usr/share/zoneinfo)
2021-03-13 16:51:03.411 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/media/audio/ui)
2021-03-13 16:51:03.462 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/lib64)
2021-03-13 16:51:03.523 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/lib)
2021-03-13 16:51:03.583 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/framework)
2021-03-13 16:51:03.651 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/etc/permissions)
2021-03-13 16:51:03.717 4802-4802/? W/J1: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
        at N1.a()
        at t0.c(:1)
        at I1.b(:1)
        at I1.a()
        at b0.a(:13)
        at io.github.vvb2060.magiskdetector.MainActivity.onStart(:8)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6709)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
2021-03-13 16:51:03.732 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/bin)
2021-03-13 16:51:03.823 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/sbin)
2021-03-13 16:51:03.911 4825-4825/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/etc/mkshrc)
2021-03-13 16:51:03.911 4825-4825/? I/IsolatedMagiskHider: Unmounted magisk file system.
2021-03-13 16:51:04.085 4825-4825/? W/re-initialized>: type=1400 audit(0.0:81): avc: denied { getattr } for path="/data/data/io.github.vvb2060.magiskdetector" dev="mmcblk0p22" ino=488927 scontext=u:r:isolated_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
2021-03-13 16:51:04.110 4825-4825/? I/art: Starting a blocking GC Xposed
2021-03-13 16:51:04.152 4825-4825/? V/ActivityThread: SVC-Creating service CreateServiceData{token=android.os.BinderProxy@9f39436 className=io.github.vvb2060.magiskdetector.RemoteService packageName=io.github.vvb2060.magiskdetector intent=null}
2021-03-13 16:51:04.216 4802-4802/? W/J1: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
        at N1.a()
        at t0.c(:1)
        at I1.b(:1)
        at I1.a()
        at b0.a(:20)
        at io.github.vvb2060.magiskdetector.MainActivity.onStart(:8)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6709)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
2021-03-13 16:51:04.426 4802-4802/? I/MagiskDetector: spFingerprint= 
      fingerprint=XXX
2021-03-13 16:51:04.429 4802-4802/? I/MagiskDetector: spBootId= 
      bootId=XXX
```

**Comment by canyie** [comment]
> Test results: Need to restart to complete detection

just reboot and test it again

**Comment by Stillhard** [comment]
> > Test results: Need to restart to complete detection
> 
> just reboot and test it again

Still detected
Test Results: Magisk module modified at least one system file
```
2021-03-14 04:54:34.349 309-309/? I/IsolatedMagiskHider: Changed mount mode from MOUNT_EXTERNAL_NONE to MOUNT_EXTERNAL_DEFAULT
2021-03-14 04:54:34.373 1418-1960/? I/ActivityManager: AMS: *** Start proc 4500:io.github.vvb2060.magiskdetector/u0i2 for service io.github.vvb2060.magiskdetector/.RemoteService
2021-03-14 04:54:34.375 4500-4500/? I/IsolatedMagiskHider: Created isolated process or app zygote 4500, starting magisk hide...
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:86): avc: denied { connectto } for path=006D6F62696C656C6F6764 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:mobile_log_d:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.392 3609-3609/? W/MagiskDetector: Magisk module file b3:16 /system/usr/share/zoneinfo/tzdata
2021-03-14 04:54:34.394 3609-3609/? W/MagiskDetector: xaVmUiD5 connected
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:87): avc: denied { connectto } for path=006E657464696167 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:netdiag:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:88): avc: denied { connectto } for path=007269727564 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:89): avc: denied { connectto } for path=00417564696F456666656374 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:system_app:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:90): avc: denied { connectto } for path=0063326B6167707364 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:mtk_agpsd:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.386 3609-3609/? W/.magiskdetector: type=1400 audit(0.0:91): avc: denied { connectto } for path=006770736C6F6764 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:mnld:s0 tclass=unix_stream_socket permissive=0
2021-03-14 04:54:34.402 3609-3609/? I/MagiskDetector: ioctl errno is 1
2021-03-14 04:54:34.462 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/xbin)
2021-03-14 04:54:34.502 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/usr/share/zoneinfo)
2021-03-14 04:54:34.562 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/media/audio/ui)
2021-03-14 04:54:34.653 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/lib64)
2021-03-14 04:54:34.715 2738-2753/? D/GasService: FG app changed: from com.transsion.XOSLauncher to io.github.vvb2060.magiskdetector
2021-03-14 04:54:34.733 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/lib)
2021-03-14 04:54:34.783 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/framework)
2021-03-14 04:54:34.842 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/etc/permissions)
2021-03-14 04:54:34.903 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/bin)
2021-03-14 04:54:34.982 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/sbin)
2021-03-14 04:54:35.032 4500-4500/? D/IsolatedMagiskHider: hide_policy: Unmounted (/system/etc/mkshrc)
2021-03-14 04:54:35.032 4500-4500/? I/IsolatedMagiskHider: Unmounted magisk file system.
2021-03-14 04:54:35.144 3609-3609/? I/MagiskDetector: spFingerprint=XXX 
      fingerprint=XXX
2021-03-14 04:54:35.148 3609-3609/? I/MagiskDetector: spBootId=XXX
      bootId=XXX
```

This line:
`2021-03-14 04:54:34.392 3609-3609/? W/MagiskDetector: Magisk module file b3:16 /system/usr/share/zoneinfo/tzdata`

**Comment by Stillhard** [comment]
Fixed in https://github.com/canyie/Riru-IsolatedMagiskHider/commit/a909331c5e363796d11c274af28c7e68499c3764
